app = "codepulse"
primary_region = "iad"

[build]
dockerfile = "Dockerfile"

[http_service]
auto_start_machines = true
auto_stop_machines = "default"
force_https = true
internal_port = 3_000
min_machines_running = 0
max_machines_running = 1
[[vm]]
memory = "512mb"
size = "shared-cpu-2x"
    
