app = "codepulse"
primary_region = "sin"

[build]
dockerfile = "Dockerfile"

[http_service]
auto_start_machines = true
auto_stop_machines = "stop"
force_https = true
internal_port = 3_000
min_machines_running = 1

  [[http_service.checks]]
  grace_period = "30s"
  interval = "30s"
  method = "GET"
  path = "/api/health"
  timeout = "5s"

[[vm]]
memory = "512mb"
size = "shared-cpu-2x"
    
