import {
  GEMMA_API_URL,
  GEMMA_MODEL,
  GEMMA_ACCESS_CLIENT_ID,
  GEMMA_ACCESS_CLIENT_SECRET,
  AI_REQUEST_TIMEOUT_MS,
} from '../../../config/index.js'
import { getAiExplanationsCollection, getTechnicalDebtMetricsCollection } from '../../../db/index.js'
import {
  getRepositoryScore,
  getRepositoryKnowledgeDrift,
  serializeAnalysisScores,
  serializeKnowledgeDrift,
} from './analysisStore.js'

/**
 * Prompt/response contract version. Bump when the prompt shape or the parsed
 * output schema changes so stored explanations can be told apart from
 * explanations generated by a previous contract.
 */
export const PROMPT_VERSION = 1

export class AiNotConfiguredError extends Error {
  constructor(message = 'AI explanations are not configured for this deployment.') {
    super(message)
    this.name = 'AiNotConfiguredError'
  }
}

export class AiProviderError extends Error {
  constructor(message) {
    super(message)
    this.name = 'AiProviderError'
  }
}

export function isAiExplainabilityConfigured() {
  return Boolean(GEMMA_API_URL && GEMMA_MODEL)
}

function buildHeaders() {
  const headers = { 'Content-Type': 'application/json', Accept: 'application/json' }
  if (GEMMA_ACCESS_CLIENT_ID) headers['CF-Access-Client-Id'] = GEMMA_ACCESS_CLIENT_ID
  if (GEMMA_ACCESS_CLIENT_SECRET) headers['CF-Access-Client-Secret'] = GEMMA_ACCESS_CLIENT_SECRET
  return headers
}

/**
 * Calls the self-hosted Gemma model behind an Ollama-compatible /api/chat
 * endpoint. Repository content is never sent — only the smallest relevant
 * evidence assembled by the prompt builders below.
 */
export async function callGemma({ system, user }) {
  if (!isAiExplainabilityConfigured()) {
    throw new AiNotConfiguredError()
  }

  const controller = new AbortController()
  const timer = setTimeout(() => controller.abort(), AI_REQUEST_TIMEOUT_MS)

  let response
  try {
    response = await fetch(`${GEMMA_API_URL}/api/chat`, {
      method: 'POST',
      headers: buildHeaders(),
      signal: controller.signal,
      body: JSON.stringify({
        model: GEMMA_MODEL,
        stream: false,
        messages: [
          { role: 'system', content: system },
          { role: 'user', content: user },
        ],
        options: { temperature: 0.2 },
      }),
    })
  } catch (error) {
    if (error.name === 'AbortError') {
      throw new AiProviderError('The AI explanation request timed out.')
    }
    throw new AiProviderError(`Unable to reach the AI explanation service: ${error.message}`)
  } finally {
    clearTimeout(timer)
  }

  const text = await response.text()
  let payload = {}
  try {
    payload = text ? JSON.parse(text) : {}
  } catch {
    throw new AiProviderError('The AI explanation service returned an unreadable response.')
  }

  if (!response.ok) {
    const detail = payload?.error ? ` ${payload.error}` : ''
    throw new AiProviderError(`AI explanation service failed with status ${response.status}.${detail}`)
  }

  const content = payload?.message?.content
  if (typeof content !== 'string' || !content.trim()) {
    throw new AiProviderError('The AI explanation service returned an empty response.')
  }

  return content.trim()
}

function formatEvidenceList(reasons) {
  return reasons.length > 0 ? reasons.map(reason => `- ${reason}`).join('\n') : '- No specific evidence captured.'
}

/** Prompt Blueprint 2 (docs/ai/AI_ENGINE.md) — risk explanation & refactor plan. */
export function buildRiskExplanationPrompt(module) {
  const system = `You are CodePulse-Refactor-Copilot, an expert software architect.
You explain complex code issues (Technical and Knowledge Debt) in simple terms and recommend actionable refactoring plans.
Ensure recommendations prioritize architectural soundness, decoupling, and maintainability.`

  const user = `The module "${module.path}" is categorized as ${(module.risk || 'Unknown').toUpperCase()} RISK with a score of ${module.debtScore ?? 0}/100.
Analyze the following metrics to generate an explanation and action plan.

--- ANALYTICAL METRICS ---
- Complexity: ${module.complexity ?? 0} (method: ${module.complexityMethod || 'metadata-heuristic'})
- Code Duplication: ${module.duplicationPercent ?? 'unknown'}%
- Churn Rate: ${module.churnPercent ?? 0}% of recent changes
- Circular Dependency: ${module.inCircularDependency ? 'Yes' : 'No'}
- Contributor Concentration: ${module.contributorConcentrationPercent ?? 0}% (key-person risk index)
- Dependency Depth: ${module.dependencyDepth ?? 0}

--- EVIDENCE ---
${formatEvidenceList(module.reasons || [])}

Provide your findings in JSON format only, with no prose outside the JSON object:
{
  "explanation": "A concise explanation of why the module has accumulated high risk.",
  "implications": ["Impact on onboarding", "Regression risks during updates", "Testing difficulty"],
  "action_plan": [
    { "step": 1, "title": "Refactoring task title", "description": "Step-by-step technical instructions", "priority": "High" }
  ]
}`

  return { system, user }
}

function stripCodeFence(text) {
  const fenced = text.match(/```(?:json)?\s*([\s\S]*?)```/i)
  return (fenced ? fenced[1] : text).trim()
}

export function parseRiskExplanationResponse(rawText) {
  let parsed
  try {
    parsed = JSON.parse(stripCodeFence(rawText))
  } catch {
    throw new AiProviderError('The AI explanation service returned invalid JSON.')
  }

  if (
    !parsed
    || typeof parsed.explanation !== 'string'
    || !Array.isArray(parsed.implications)
    || !Array.isArray(parsed.action_plan)
  ) {
    throw new AiProviderError('The AI explanation service returned an unexpected response shape.')
  }

  return {
    explanation: parsed.explanation,
    implications: parsed.implications.filter(item => typeof item === 'string'),
    actionPlan: parsed.action_plan
      .filter(step => step && typeof step === 'object')
      .map((step, index) => ({
        step: Number.isFinite(step.step) ? step.step : index + 1,
        title: typeof step.title === 'string' ? step.title : 'Refactoring step',
        description: typeof step.description === 'string' ? step.description : '',
        priority: typeof step.priority === 'string' ? step.priority : 'Medium',
      })),
  }
}

/** Prompt Blueprint 3 (docs/ai/AI_ENGINE.md) — executive health summary. */
export function buildExecutiveSummaryPrompt({ repositoryName, scores, topRisks, topDrift }) {
  const system = 'You are CodePulse-Executive-Reporter. You summarize repository health, highlighting key technical debt trends and knowledge risks for engineering leadership.'

  const risksText = topRisks.length > 0
    ? topRisks.map(module => `- ${module.path} (risk ${module.risk || 'Unknown'}, score ${module.debtScore ?? 0}/100)`).join('\n')
    : '- No high-risk modules identified.'
  const driftText = topDrift.length > 0
    ? topDrift.map(finding => `- ${finding.filePath}: ${finding.title} (${finding.severity})`).join('\n')
    : '- No documentation drift findings recorded.'

  const user = `Repository: ${repositoryName || 'Unknown repository'}
Overall Health Score: ${scores.healthScore ?? 0}/100
Technical Debt Grade: ${scores.technicalDebt?.grade || 'A'}
Knowledge Debt Score: ${scores.knowledgeDebt?.score ?? 0}/100

Top 3 Risk Modules:
${risksText}

Top 3 Documentation Drift Issues:
${driftText}

Write a concise 3-paragraph executive summary detailing:
1. The current health status of the repository and its main maintainability bottleneck.
2. A summary of the key-person and documentation coverage risks.
3. The top two immediate recommendations to improve developer velocity and sustainability.`

  return { system, user }
}

function moduleRecordToPromptInput(record) {
  return {
    path: record.file_path,
    risk: record.risk,
    debtScore: record.debt_score ?? 0,
    complexity: record.complexity ?? 0,
    complexityMethod: record.complexity_method,
    duplicationPercent: record.duplication_percent ?? null,
    churnPercent: record.churn_percent ?? 0,
    inCircularDependency: Boolean(record.is_circular),
    contributorConcentrationPercent: record.contributor_concentration_percent ?? 0,
    dependencyDepth: record.dependency_depth ?? 0,
    reasons: Array.isArray(record.reasons) ? record.reasons : [],
  }
}

function serializeExplanationRecord(record) {
  const createdAt = record.created_at instanceof Date ? record.created_at : new Date(record.created_at)
  return {
    id: record._id?.toString?.() || record.id?.toString?.() || null,
    kind: record.kind,
    key: record.key,
    model: record.model,
    promptVersion: record.prompt_version,
    output: record.output,
    generatedAt: Number.isNaN(createdAt.getTime()) ? null : createdAt.toISOString(),
  }
}

const defaultDeps = {
  isAiExplainabilityConfigured,
  callGemma,
  getRepositoryScore,
  getRepositoryKnowledgeDrift,
  serializeAnalysisScores,
  serializeKnowledgeDrift,
  getTechnicalDebtMetricsCollection,
  getAiExplanationsCollection,
  now: () => new Date(),
}

/**
 * Orchestrates AI Explainability generation: assembles the smallest relevant
 * evidence already stored by the deterministic analysis pipeline, calls the
 * model, validates structured output, and persists it for traceability. AI
 * generation is opt-in per call and never replaces the deterministic scores
 * or recommendations.
 */
export function createAiExplainabilityService(deps = defaultDeps) {
  async function findModuleRecord(repositoryId, modulePath) {
    const collection = await deps.getTechnicalDebtMetricsCollection()
    return collection.findOne({ repository_id: repositoryId, file_path: modulePath })
  }

  async function persistExplanation({ repositoryId, kind, key, model, output }) {
    const collection = await deps.getAiExplanationsCollection()
    const now = deps.now()
    const record = {
      repository_id: repositoryId,
      kind,
      key,
      prompt_version: PROMPT_VERSION,
      model,
      output,
      created_at: now,
    }
    const result = await collection.insertOne(record)
    return { ...record, _id: result.insertedId }
  }

  async function getCachedRecord(repositoryId, kind, key) {
    const collection = await deps.getAiExplanationsCollection()
    return collection.find({ repository_id: repositoryId, kind, key }).sort({ created_at: -1 }).limit(1).next()
  }

  async function generateRiskExplanation(repositoryId, modulePath) {
    if (!deps.isAiExplainabilityConfigured()) {
      return { kind: 'not-configured' }
    }

    const moduleRecord = await findModuleRecord(repositoryId, modulePath)
    if (!moduleRecord) {
      return { kind: 'module-not-found' }
    }

    const prompt = buildRiskExplanationPrompt(moduleRecordToPromptInput(moduleRecord))
    const rawText = await deps.callGemma(prompt)
    const parsed = parseRiskExplanationResponse(rawText)
    const record = await persistExplanation({
      repositoryId,
      kind: 'risk',
      key: modulePath,
      model: GEMMA_MODEL,
      output: parsed,
    })

    return { kind: 'generated', explanation: serializeExplanationRecord(record) }
  }

  async function generateExecutiveSummary(repositoryId, repositoryName) {
    if (!deps.isAiExplainabilityConfigured()) {
      return { kind: 'not-configured' }
    }

    const scoreRecord = await deps.getRepositoryScore(repositoryId)
    if (!scoreRecord) {
      return { kind: 'analysis-unavailable' }
    }

    const driftResult = await deps.getRepositoryKnowledgeDrift(repositoryId)
    const technicalDebtCollection = await deps.getTechnicalDebtMetricsCollection()
    const topRiskRecords = await technicalDebtCollection
      .find({ repository_id: repositoryId })
      .sort({ debt_score: -1 })
      .limit(3)
      .toArray()

    const scores = deps.serializeAnalysisScores(scoreRecord)
    const drift = deps.serializeKnowledgeDrift(driftResult?.score, driftResult?.findings)
    const topRisks = topRiskRecords.map(record => ({
      path: record.file_path,
      risk: record.risk,
      debtScore: record.debt_score ?? 0,
    }))
    const topDrift = (drift?.findings || []).slice(0, 3)

    const prompt = buildExecutiveSummaryPrompt({ repositoryName, scores, topRisks, topDrift })
    const rawText = await deps.callGemma(prompt)
    const record = await persistExplanation({
      repositoryId,
      kind: 'summary',
      key: 'executive-summary',
      model: GEMMA_MODEL,
      output: { summary: rawText },
    })

    return { kind: 'generated', explanation: serializeExplanationRecord(record) }
  }

  async function getRiskExplanation(repositoryId, modulePath) {
    const record = await getCachedRecord(repositoryId, 'risk', modulePath)
    return record ? serializeExplanationRecord(record) : null
  }

  async function getExecutiveSummary(repositoryId) {
    const record = await getCachedRecord(repositoryId, 'summary', 'executive-summary')
    return record ? serializeExplanationRecord(record) : null
  }

  return {
    isAiExplainabilityConfigured: deps.isAiExplainabilityConfigured,
    generateRiskExplanation,
    generateExecutiveSummary,
    getRiskExplanation,
    getExecutiveSummary,
  }
}

export const aiExplainabilityService = createAiExplainabilityService()
